In [39]:
from IPython.display import Latex
import numpy as np
import random
import scipy.optimize as optimize

$f(x_1,x_2,x_3) = 100(x_1 - x_2^{2}) - (x_1 - 1)^2 - 90(x_2 - x_3^{2}) - (x_2 - 1)^2$

In [40]:
def f(params):
    x1, x2, x3 = params
    return 100*(x1- (x2**2)) - (x1 - 1)**2 - 90*(x2-(x3**3))**2 - (x2 -1)**2

In [41]:
initial_guess = [0, 0, 0]


In [45]:
result = optimize.minimize(f, initial_guess)
print(result.x)

[-1.85229600e+09 -3.63194777e+07  0.00000000e+00]


In [46]:
result = optimize.minimize(f, initial_guess,method="Nelder-Mead")
print(result.x)

[-8.31799569e+50  1.90900722e+50  2.17813802e+50]


In [47]:
result = optimize.minimize(f, initial_guess,method="L-BFGS-B")
print(result.x)


[-6.53067413e+08 -1.28052311e+07  0.00000000e+00]
